# Sidebar navigation

- label: 'Home'
  link: '/'
- label: Strength Training
  items:
    - label: 'All'
      link: '/strength-training/st-all'
    - label: 'Warmup'
      link: '/strength-training/warmup'
    - label: 'Lower Body Strength'
      link: '/strength-training/lower-body-strength'
    - label: 'Upper Body Strength'
      link: '/strength-training/page-3'
    - label: 'Stretches'
      link: '/strength-training/page-4'
- label: Section 2
  items:
    - label: 'Page 1'
      link: '/section-2/page-1'
    - label: 'Page 2'
      link: '/section-2/page-2'
    - label: 'Page 3'
      link: '/section-2/page-3'
    - label: 'Page 4'
      link: '/section-2/page-4'
- label: More
  items:
    - label: Contact
      link: /contact
    - label: 'External Link'
      link: https://github.com/rocketseat/gatsby-themes
