# Sidebar navigation

- label: 'Home'
  link: '/'
- label: Strength Training
  items:
    - label: 'All Strength Trainings'
      link: '/strength-training/strength-all'
    - label: 'Warmup'
      link: '/strength-training/strength-warmup'
    - label: 'Lower Body Strength'
      link: '/strength-training/strength-lower-body'
    - label: 'Upper Body Strength'
      link: '/strength-training/strength-upper-body'
    - label: 'Stretches'
      link: '/strength-training/strength-stretches'
- label: Agility Training
  items:
    - label: 'All Agility Trainings'
      link: '/agility-training/agility-all'
    - label: 'Agility 2'
      link: '/agility-training/agility-2'
    - label: 'Agility 3'
      link: '/agility-training/agility-3'
    - label: 'Agility 4'
      link: '/agility-training/agility-4'
- label: More
  items:
    - label: Contact
      link: /contact
    - label: 'External Link1'
      link: https://github.com/rocketseat/gatsby-themes
